import * as React from 'react'
import { Link, useParams } from 'react-router-dom'
import {
  ArrowLeftIcon,
  ArrowRightIcon,
  CheckIcon,
  LinkIcon,
  SearchXIcon,
} from 'lucide-react'

import { formatPostDate, getPost, getRelatedPosts } from '@/lib/blog'
import { SITE } from '@/lib/site'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Separator } from '@/components/ui/separator'
import { PixelSky } from '@/components/pixel/pixel-sky'
import { PostMeta } from '@/pages/BlogIndexPage'

function BlogPostPage() {
  const { slug } = useParams<{ slug: string }>()
  const post = slug ? getPost(slug) : undefined

  // Keep the document title in sync for sharing and browser history.
  React.useEffect(() => {
    if (!post) return
    const previous = document.title
    document.title = `${post.title} — ${SITE.name}`
    return () => {
      document.title = previous
    }
  }, [post])

  if (!post) return <PostNotFound />

  const related = getRelatedPosts(post)

  return (
    <>
      <PixelSky className="border-b border-border">
        <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 sm:py-20">
          <Button asChild variant="ghost" size="sm" className="-ml-3 mb-6">
            <Link to="/blog">
              <ArrowLeftIcon />
              Todos los artículos
            </Link>
          </Button>

          <div className="flex flex-wrap gap-2">
            {post.tags.map((tag) => (
              <Badge key={tag} variant="pixel">
                {tag}
              </Badge>
            ))}
          </div>

          <h1 className="mt-5 text-4xl font-extrabold tracking-tight text-balance sm:text-5xl">
            {post.title}
          </h1>

          {post.excerpt ? (
            <p className="text-muted-foreground mt-5 text-lg leading-relaxed text-pretty">
              {post.excerpt}
            </p>
          ) : null}

          <PostMeta post={post} className="mt-7" />
        </div>
      </PixelSky>

      <article className="py-14 sm:py-16">
        <div className="mx-auto max-w-3xl px-4 sm:px-6">
          {/* Body is generated by `marked` from repo-authored markdown, so the
              only HTML here is content we commit ourselves. */}
          <div
            className="prose-nubitlan"
            dangerouslySetInnerHTML={{ __html: post.html }}
          />

          <Separator className="my-12" />

          <div className="flex flex-wrap items-center justify-between gap-4">
            <p className="text-muted-foreground font-mono text-sm">
              Publicado el {formatPostDate(post.date)}
            </p>
            <CopyLinkButton />
          </div>
        </div>
      </article>

      {related.length > 0 ? (
        <section className="bg-sky-50 py-16 dark:bg-sky-950/60">
          <div className="mx-auto max-w-4xl px-4 sm:px-6">
            <h2 className="eyebrow text-primary">Sigue leyendo</h2>
            <div className="mt-6 grid gap-5 sm:grid-cols-2">
              {related.map((item) => (
                <Link key={item.slug} to={`/blog/${item.slug}`} className="group">
                  <Card className="h-full transition-all duration-300 group-hover:-translate-y-1 group-hover:shadow-lg">
                    <CardContent className="p-6">
                      <h3 className="group-hover:text-primary text-lg font-bold tracking-tight transition-colors">
                        {item.title}
                      </h3>
                      <p className="text-muted-foreground mt-2 text-sm leading-relaxed">
                        {item.excerpt}
                      </p>
                      <span className="text-primary mt-4 inline-flex items-center gap-1.5 text-sm font-semibold">
                        Leer
                        <ArrowRightIcon className="size-4 transition-transform group-hover:translate-x-1" />
                      </span>
                    </CardContent>
                  </Card>
                </Link>
              ))}
            </div>
          </div>
        </section>
      ) : null}

      <section className="py-16">
        <div className="mx-auto max-w-2xl px-4 text-center sm:px-6">
          <h2 className="text-2xl font-extrabold tracking-tight text-balance">
            ¿Quieres evaluar tu propia empresa?
          </h2>
          <p className="text-muted-foreground mt-3">
            Haz nuestra evaluación gratuita y recibe recomendaciones
            priorizadas.
          </p>
          <Button asChild variant="pixel" size="lg" className="mt-7">
            <Link to="/evaluacion">
              Comenzar evaluación
              <ArrowRightIcon />
            </Link>
          </Button>
        </div>
      </section>
    </>
  )
}

function CopyLinkButton() {
  const [copied, setCopied] = React.useState(false)

  const copy = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Clipboard access can be denied (insecure context, permissions);
      // there is nothing useful to recover to, so leave the label unchanged.
    }
  }

  return (
    <Button variant="pixelOutline" size="sm" onClick={copy}>
      {copied ? <CheckIcon /> : <LinkIcon />}
      {copied ? 'Enlace copiado' : 'Copiar enlace'}
    </Button>
  )
}

function PostNotFound() {
  return (
    <section className="py-24">
      <div className="mx-auto max-w-lg px-4 text-center sm:px-6">
        <SearchXIcon className="text-muted-foreground mx-auto size-12" />
        <h1 className="mt-6 text-3xl font-extrabold tracking-tight">
          Artículo no encontrado
        </h1>
        <p className="text-muted-foreground mt-4">
          El artículo que buscas no existe o fue movido.
        </p>
        <Button asChild variant="pixel" className="mt-8">
          <Link to="/blog">
            <ArrowLeftIcon />
            Ver todos los artículos
          </Link>
        </Button>
      </div>
    </section>
  )
}

export default BlogPostPage
